PortfolioMVC5v3/Controllers/AboutMeController.cs
using Newtonsoft.Json;
using PortfolioMVC5v3.Logic.Interfaces;
using PortfolioMVC5v3.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PortfolioMVC5v3.Controllers
{
    public class AboutMeController : Controller
    {
        private readonly IAboutMeLogic _aboutMeLogic;
        private readonly ITechnologyLogic _technologyLogic;


        public AboutMeController(IAboutMeLogic aboutMeLogic, ITechnologyLogic technologyLogic)
        {
            _aboutMeLogic = aboutMeLogic;
            _technologyLogic = technologyLogic;
        }

        public async Task<ActionResult> Index()
        {
            var model = await _aboutMeLogic.GetAboutMeAsync();

            return model == null ? View("Error") : View(model);
        }

        public ActionResult GetSkillsPartialView()
        {
            var technologies = _technologyLogic.GetTechnologiesToShowInAboutMePage();

            return PartialView("SkillsPartialView", technologies ?? new List<Technology>());
        }

        public async Task<ActionResult> Management()
        {
            var pageData = await _aboutMeLogic.GetAboutMeAsync();

            return pageData == null ? View("Error") : View(pageData);

        }

        [HttpPost]
        public async Task<ActionResult> Update(AboutMe aboutMe, List<int> selectedTechnologies)
        {
            var result = await _aboutMeLogic.UpdateAboutMeAsync(aboutMe) && await _technologyLogic.UpdateShowInAboutMeTechnologiesAsync(selectedTechnologies);

            return Json(new { success = result });
        }

        public async Task<string> GetAllTechnologiesListAsync()
        {
            var technologies = await _technologyLogic.GetAllTechnologiesListAsync();

            return JsonConvert.SerializeObject(technologies);
        }

        public string GetTechnologiesToShowInAboutMePage()
        {
            var technologies = _technologyLogic.GetTechnologiesToShowInAboutMePage();

            return JsonConvert.SerializeObject(technologies);

        }
    }
}

PortfolioMVC5v3/Controllers/ContactController.cs
using PortfolioMVC5v3.Utilities;
using System;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;

namespace PortfolioMVC5v3.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendEmail(string email, string subject, string message, string name)
        {
            SmtpClient client = new SmtpClient("smtp.webio.pl")
            {
                Credentials = new NetworkCredential("Portfolio@damiandziura.pl", "Damian131"),
                Port = 465,
                EnableSsl = true,
                
            };

            MailMessage mailMessage = new MailMessage
            {
                From = new MailAddress(email)
            };
            mailMessage.To.Add("Kontakt@DamianDziura.pl");
            mailMessage.Subject = $"{subject} - {name}";
            mailMessage.Body = message;

            try
            {
                client.SendMailAsync(mailMessage);
            }
            catch (Exception e)
            {
                Logger.Log(e);
            }

            return new HttpStatusCodeResult(200);

        }
    }
}

PortfolioMVC5v3/Controllers/CvController.cs
using System.Threading.Tasks;
using PortfolioMVC5v3.Logic.Interfaces;
using System.Web.Mvc;

namespace PortfolioMVC5v3.Controllers
{
    public class CvController : Controller
    {
        private readonly ICvLogic _cvLogic;

        public CvController(ICvLogic cvLogic)
        {
            _cvLogic = cvLogic;
        }
        
        public async Task<ActionResult> Index()
        {
            var cvViewModel = await _cvLogic.GetCvViewModel();

            return View(cvViewModel);
        }

        public async Task<ActionResult> SaveAsPdf()
        {
            var cvViewModel = await _cvLogic.GetCvViewModel();

            return View(cvViewModel);
        }

        [Authorize]
        [Authorize(Roles = "Admin")]
        public ActionResult Management()
        {

            return View();
        }
    }
}

PortfolioMVC5v3/Controllers/IconController.cs
using Newtonsoft.Json;
using PortfolioMVC5v3.Logic.Interfaces;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PortfolioMVC5v3.Controllers
{
    [Authorize]
    [Authorize(Roles = "Admin")]
    public class IconController : Controller
    {
        private readonly IIconLogic _iconLogic;

        public IconController(IIconLogic iconLogic)
        {
            _iconLogic = iconLogic;
        }

        public ActionResult Management()
        {
            return View();
        }

        public async Task<string> GetAllIcons()
        {
            var icons = await _iconLogic.GetAllIcons();

            return JsonConvert.SerializeObject(icons);
        }

        public ActionResult AddIcon()
        {
            return View();
        }

        public async Task<ActionResult> UploadIcon(HttpPostedFileBase iconFile)
        {
            await _iconLogic.AddIconAsync(iconFile);

            return RedirectToAction("Management");
        }

        public async Task<ActionResult> RemoveIcon(int id)
        {
            var result = await _iconLogic.RemoveIconAsync(id);

            return new HttpStatusCodeResult(result ? 200 : 500);
        }

        public async Task<string> GetIcons()
        {
            var icons = await _iconLogic.GetAllIcons();
            return JsonConvert.SerializeObject(icons);
        }

    }
}

PortfolioMVC5v3/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Panel administracyjny">
    <meta name="author" content="Damian Dziura">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon.ico">
    <title>Damian Dziura portfolio - Panel administracyjny</title>

    @Styles.Render("~/Content/adminCss")
    <!-- Kendo UI combined JavaScript -->
    @RenderSection("AdditionalCss", false)
    <style>
        html, body {
            height: 100%;
        }

        .btn-primary {
            color: #fff;
            background-color: #27a9e3;
            border-color: #27a2d9;
        }

            .btn-primary:hover {
                color: #fff;
                background-color: #2190c2;
                border-color: #2190c2;
            }

            .btn-primary:focus, .btn-primary.focus {
                -webkit-box-shadow: 0 0 0 0.2rem #27a2d9;
                -webkit-box-shadow: 0 0 0 0.2rem rgba(39, 162, 217, 0.5);
                box-shadow: 0 0 0 0.2rem #27a2d9;
                box-shadow: 0 0 0 0.2rem rgba(39, 162, 217, 0.5);
            }

            .btn-primary.disabled, .btn-primary:disabled {
                color: #fff;
                background-color: #27a9e3;
                border-color: #27a2d9;
            }

            .btn-primary:not(:disabled):not(.disabled):active, .btn-primary:not(:disabled):not(.disabled).active,
            .show > .btn-primary.dropdown-toggle {
                color: #fff;
                background-color: #27a9e3;
                border-color: #27a2d9;
            }

                .btn-primary:not(:disabled):not(.disabled):active:focus, .btn-primary:not(:disabled):not(.disabled).active:focus,
                .show > .btn-primary.dropdown-toggle:focus {
                    -webkit-box-shadow: 0 0 0 0.2rem #27a2d9;
                    -webkit-box-shadow: 0 0 0 0.2rem rgba(39, 162, 217, 0.5);
                    box-shadow: 0 0 0 0.2rem #27a2d9;
                    box-shadow: 0 0 0 0.2rem rgba(39, 162, 217, 0.5);
                }
    </style>
</head>
<body>
    <div id="main-wrapper" style="height: 100%;">
        <header class="topbar" data-navbarbg="skin5">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin5">
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu"></i></a>

                    <a class="navbar-brand" href="@Url.Action("Dashboard", "AdministratorPanel")">
                        <b class="logo-icon p-l-10">
                            <img src="~/Assets/img/logo.png" alt="homepage" class="light-logo" />
                        </b>
                    </a>
                </div>
            </nav>
        </header>


        <aside class="left-sidebar" data-sidebarbg="skin5">
            <div class="scroll-sidebar">
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="p-t-30">
                        @Html.Partial("_NavigateAdministratorPanelPartialView")
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="page-wrapper h-100">
            <div class="container-fluid h-100">
                @RenderBody()
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/adminLayout")
    <script type="text/javascript">
        kendo.culture("pl-PL");
    </script>
    @RenderSection("scripts", required: false)

</body>
</html>

PortfolioMVC5v3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Damian Dziura Portfolio</title>
    @Styles.Render("~/Content/css")
    @RenderSection("AdditionalCss", false)
</head>
<body>

    <div class="container-fluid p-0 m-0 h-100">
        @Html.Partial("_NavigatePartialView")
        @RenderBody()
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PortfolioMVC5v3/Views/Shared/_NavigateAdministratorPanelPartialView.cshtml
<li class="sidebar-item"> <a class="sidebar-link waves-effect sidebar-link" href="@Url.Action("Dashboard", "AdministratorPanel")" aria-expanded="false"><i class="fas fa-cog"></i><span class="hide-menu">Dashboard</span></a></li>
<li class="sidebar-item"> <a class="sidebar-link waves-effect sidebar-link" href="@Url.Action("List", "Technologies")" aria-expanded="false"><i class="fas fa-chart-pie"></i><span class="hide-menu">Technologie</span></a></li>
<li class="sidebar-item"> <a class="sidebar-link waves-effect sidebar-link" href="@Url.Action("Management", "Icon")" aria-expanded="false"><i class="fas fa-images"></i><span class="hide-menu">Ikony</span></a></li>

<li class="sidebar-item">
    <a class="sidebar-link has-arrow waves-effect" href="javascript:void(0)" aria-expanded="false"><i class="fas fa-project-diagram"></i><span class="hide-menu">Projekty</span></a>
    <ul aria-expanded="false" class="collapse  first-level">
        <li class="sidebar-item"><a href="@Url.Action("ManagementCard", "Project")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> Utwórz projekt</span></a></li>
        <li class="sidebar-item"><a href="@Url.Action("ProjectManagement", "Project")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> Lista projektów</span></a></li>
        <li class="sidebar-item"><a href="@Url.Action("TempProjectManagement", "Project")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> Tymczasowe projekty</span></a></li>
    </ul>
</li>

<li class="sidebar-item">
    <a class="sidebar-link has-arrow waves-effect" href="javascript:void(0)" aria-expanded="false"><i class="fas fa-file-alt"></i><span class="hide-menu">Zarządzanie Cv</span></a>
    <ul aria-expanded="false" class="collapse  first-level">
        <li class="sidebar-item"><a href="@Url.Action("Management", "Cv")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> Edytuj Cv</span></a></li>
        <li class="sidebar-item"><a href="@Url.Action("List", "Achievements")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> Osiągnięcia</span></a></li>
        <li class="sidebar-item"><a href="@Url.Action("List", "ExtraInformations")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> Dodatkowe informacje</span></a></li>
        <li class="sidebar-item"><a href="@Url.Action("List", "EmploymentHistory")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> Historia zatrudnienia</span></a></li>
        <li class="sidebar-item"><a href="@Url.Action("List", "Education")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> Wykształcenie</span></a></li>
    </ul>
</li>

<li class="sidebar-item">
    <a class="sidebar-link has-arrow waves-effect" href="javascript:void(0)" aria-expanded="false"><i class="fas fa-address-card"></i><span class="hide-menu">Strony</span></a>
    <ul aria-expanded="false" class="collapse  first-level">
        <li class="sidebar-item"><a href="@Url.Action("Management", "AboutMe")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> O mnie</span></a></li>
        <li class="sidebar-item"><a href="@Url.Action("Management", "Home")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> Główna strona</span></a></li>
    </ul>
</li>

<li class="sidebar-item">
    <a class="sidebar-link has-arrow waves-effect" href="javascript:void(0)" aria-expanded="false"><i class="fas fa-users"></i><span class="hide-menu">Użytkownicy</span></a>
    <ul aria-expanded="false" class="collapse  first-level">
        <li class="sidebar-item"><a href="@Url.Action("Management", "Account")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> Użytkownicy</span></a></li>
        <li class="sidebar-item"><a href="@Url.Action("RoleManagement", "Account")" class="sidebar-link"><i class="fas fa-caret-right"></i><span class="hide-menu"> Role</span></a></li>
    </ul>
</li>


<li class="sidebar-item"> <a class="sidebar-link waves-effect sidebar-link" href="@Url.Action("Index", "Home")" aria-expanded="false"><i class="fas fa-sign-out-alt"></i><span class="hide-menu">Powrót do portfolio</span></a></li>

PortfolioMVC5v3/Views/Shared/_NavigatePartialView.cshtml
@using Microsoft.AspNet.Identity
<nav>
    <div class="logo">
        <img src="../../Assets/img/logo.png" alt="" />
    </div>
    <div class="mini-logo">
        <img src="../../Assets/img/mini_logo.png" alt="" />
    </div>

    <ul>
        <li>
            <a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i><em>Strona główna</em></a>
        </li>
        <li>
            <a href="@Url.Action("Index", "AboutMe")"><i class="fa fa-user"></i><em>O mnie</em></a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Project")"><i class="fas fa-project-diagram"></i><em>Projekty</em></a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Cv")"><i class="fas fa-file-alt"></i><em>CV</em></a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Contact")"><i class="fa fa-envelope"></i><em>Kontakt</em></a>
        </li>
        @if (Request.IsAuthenticated)
        {
            if (User.IsInRole("Admin"))
            {
                <li>
                    <a href="@Url.Action("Dashboard", "AdministratorPanel")"><i class="fas fa-tools"></i><em>Panel administratora</em></a>
                </li>
            }

            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
            {
                @Html.AntiForgeryToken()

                <li>
                    <a href="javascript:{}" onclick="document.getElementById('logoutForm').submit();"><i class="fas fa-power-off"></i><em>Wyloguj: @Html.Name(User.Identity.GetUserName())</em></a>
                </li>
            }
        }
        else
        {
            <li>
                <a href="@Url.Action("Login", "Account")"><i class="fas fa-sign-in-alt"></i><em>Zaloguj</em></a>
            </li>

        }
    </ul>
</nav>