PortfolioMVC5v3/Models/Project.cs
using System;

namespace PortfolioMVC5v3.Models
{
    public class Project
    {
        public int ProjectId { get; set; }

        public string AuthorId { get; set; }

        public int IconId { get; set; }

        public string Title { get; set; }

        public string ShortDescription { get; set; }

        public string FullDescription { get; set; }

        public bool Commercial { get; set; }

        public bool ShowInCv { get; set; }
        
        public DateTime DateTimeCreated { get; set; }
        
        public bool TempProject { get; set; }

        public string GitHubLink { get; set; }
    }
}

PortfolioMVC5v3/Models/ViewModels/ProjectViewModel.cs
using System.Collections.Generic;

namespace PortfolioMVC5v3.Models.ViewModels
{
    public class ProjectViewModel : Project
    {
        public Icon Icon { get; set; }
        public List<Technology> Technologies { get; set; }
        public List<Image> Images { get; set; }
    }
}

PortfolioMVC5v3/Controllers/ProjectController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PortfolioMVC5v3.Logic.Interfaces;
using PortfolioMVC5v3.Models;
using PortfolioMVC5v3.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

// ReSharper disable ArgumentsStyleLiteral

namespace PortfolioMVC5v3.Controllers
{
    [Authorize]
    [Authorize(Roles = "Admin")]
    public class ProjectController : Controller
    {
        private readonly IProjectLogic _projectLogic;
        private readonly ITechnologyLogic _technologyLogic;

        public ProjectController(IProjectLogic projectLogic, ITechnologyLogic technologyLogic)
        {
            _projectLogic = projectLogic;
            _technologyLogic = technologyLogic;
        }

        [AllowAnonymous]
        public async Task<ActionResult> Index()
        {
            var projects = await _projectLogic.GetProjectsViewModelList(showInCvProjects: true, tempProjects: false);

            return View(projects);
        }

        [AllowAnonymous]
        public async Task<ActionResult> Card(int id)
        {
            var project = await _projectLogic.GetProject(id);

            return View(project);
        }

        public async Task<ActionResult> ManagementCard(int? id)
        {
            ProjectViewModel project;
            if (id.HasValue)
            {
                project = await _projectLogic.GetProject(id.Value);
            }
            else project = new ProjectViewModel()
            {
                ProjectId = 0,
                Icon = new Icon(),
                AuthorId = "id",
                Commercial = false,
                DateTimeCreated = DateTime.Now,
                TempProject = false,
                ShowInCv = false
            };

            return View(project);
        }

        public ActionResult ProjectManagement()
        {
            return View(false);
        }

        public async Task<string> GetProjectsList()
        {
            var projects = await _projectLogic.GetProjectsList(showInCvProjects: null, tempProjects: false);

            return JsonConvert.SerializeObject(projects);
        }

        public async Task<string> GetTempProjectsList()
        {
            var projects = await _projectLogic.GetProjectsList(showInCvProjects: null, tempProjects: true);

            return JsonConvert.SerializeObject(projects);
        }


        public ActionResult TempProjectManagement()
        {
            return View("ProjectManagement", true);
        }

        public async Task<string> GetAllTechnologies()
        {
            var technologies = await _technologyLogic.GetAllTechnologiesListAsync();

            return JsonConvert.SerializeObject(technologies);
        }

        public async Task<string> GetCommercialProjectsToShowInCv()
        {
            var projects = await _projectLogic.GetProjectsList(true, false);
            projects = projects.Where(t => t.Commercial).ToList();

            return JsonConvert.SerializeObject(projects);
        }

        public async Task<string> GetCommercialProjectsNotShownInCv()
        {
            var projects = await _projectLogic.GetProjectsList(false, false);
            projects = projects.Where(t => t.Commercial).ToList();

            return JsonConvert.SerializeObject(projects);
        }

        public async Task<string> GetNotCommercialProjectsToShowInCv()
        {
            var projects = await _projectLogic.GetProjectsList(true, false);
            projects = projects.Where(t => t.Commercial == false).ToList();

            return JsonConvert.SerializeObject(projects);
        }

        public async Task<string> GetNotCommercialProjectsNotShownInCv()
        {
            var projects = await _projectLogic.GetProjectsList(false, false);
            projects = projects.Where(t => t.Commercial == false).ToList();

            return JsonConvert.SerializeObject(projects);
        }

        public async Task<ActionResult> AddProjectToCv(int projectId)
        {
            var result = await _projectLogic.AddProjectToCv(projectId);

            return new HttpStatusCodeResult(result ? 200 : 500);
        }

        public async Task<ActionResult> RemoveProjectFromCv(int projectId)
        {
            var result = await _projectLogic.RemoveProjectFromCv(projectId);

            return new HttpStatusCodeResult(result ? 200 : 500);
        }

        public async Task<string> CreateOrUpdateProject(ProjectViewModel projectModel)
        {
            var httpContext = System.Web.HttpContext.Current;
            string projectTechnologiesIdsJson = httpContext.Request.Form["projectTechnologiesIds"];
            List<int> projectTechnologiesIds = JsonConvert.DeserializeObject<List<int>>(projectTechnologiesIdsJson);
            if (httpContext.Request.Files.Count > 0)
            {
                string screenShootsPath = System.Web.HttpContext.Current.Server.MapPath("~/Assets/ScreenShoots/");
                projectModel.Images = new List<Image>();

                for (int i = 0; i < httpContext.Request.Files.Count; i++)
                {
                    var uploadedFile = httpContext.Request.Files[i];
                    var img = new Image()
                    {
                        FileName = $"{Guid.NewGuid().ToString()}.png",
                        Guid = Guid.NewGuid().ToString()
                    };
                    uploadedFile.SaveAs($"{screenShootsPath}{img.Guid}{img.FileName}");
                    projectModel.Images.Add(img);
                }
            }

            bool sqlResult;
            if (projectTechnologiesIds?.Count > 0) projectModel.Technologies = await _technologyLogic.GetTechnologiesByIds(projectTechnologiesIds);
            projectModel.AuthorId = User.Identity.GetUserId();

            if (projectModel.ProjectId > 0)
            {
                sqlResult = await _projectLogic.UpdateProject(projectModel);
            }
            else sqlResult = await _projectLogic.CreateProject(projectModel);

            var result = new
            {
                Success = sqlResult,
                Type = projectModel.TempProject ? "Temp" : "Normal"
            };

            return JsonConvert.SerializeObject(result);
        }

        public async Task<ActionResult> RemoveProject(int id)
        {
            var result = false;
            if (id > 0)
            {
                result = await _projectLogic.RemoveProject(id);
            }

            return new HttpStatusCodeResult(result ? 200 : 500);
        }
        
        public async Task<ActionResult> ReorderProjectsPositionsInCv(int oldPositionProjectId, int newPositionProjectId)
        {
            var result = await _projectLogic.ReorderProjectsPositionsInCv(oldPositionProjectId, newPositionProjectId);

            return new HttpStatusCodeResult(result ? 200 : 500);
        }

    }
}

PortfolioMVC5v3/Views/Project/Card.cshtml
@using PortfolioMVC5v3.Models
@model PortfolioMVC5v3.Models.ViewModels.ProjectViewModel

@{
    ViewBag.Title = "Projekt";
}
@section AdditionalCss
{
    <style>
        .slide {
            background: linear-gradient(0, rgba(40, 38, 43, 0.85), rgba(40, 38, 43, 0.85)), url(/assets/backgrounds/fourth-bg.png) no-repeat center center fixed !important;
            background-size: cover;
        }
    </style>

    @Styles.Render("~/Content/projectCardCss")

}
<div class="slide">
    <div class="content projects-content">
        <div class="container-fluid">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-9">
                        <div class="row">
                            <div class="col-12">
                                <h2>@Model.Title</h2>
                            </div>

                            <div class="col-12">
                                <h3>
                                    @if (Model.Technologies.Count > 0)
                                    {
                                        @: Technologie: <em>@string.Join(", ", Model.Technologies.Select(a => a.Name))</em>
                                    }
                                </h3>
                            </div>

                            <div class="col-12">
                                <h4>
                                    Github: <a href="@Model.GitHubLink">@Model.GitHubLink</a>
                                </h4>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12">
                                <p>@Model.FullDescription</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-3" style="min-height: 500px">
                        <div class="row">
                            <h2>Zdjęcia</h2>
                        </div>

                        <div class="row">
                            <div class="col">
                                <div class="wrap">

                                    <div class="scrollbar">
                                        <div class="handle" style="transform: translateZ(0) translateY(220px); height: 119px;">
                                            <div class="mouserea"></div>
                                        </div>
                                    </div>

                                    <div class="frame smart" id="smart" style="overflow: hidden;">
                                        <ul class="items" style="transform: translateZ(0) translateY(-1111px); height: 3030px;">
                                            @foreach (var img in Model.Images ?? new List<Image>())
                                            {
                                                <li>
                                                    <a href="~/Assets/ScreenShoots/@string.Format("{0}{1}", img.Guid, img.FileName)" data-lightbox="screenShoots">
                                                        <img src="~/Assets/ScreenShoots/@string.Format("{0}{1}", img.Guid, img.FileName)" alt="" class="img-fluid" />
                                                    </a>
                                                </li>
                                            }
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        var images = @Html.Raw(Json.Encode(@Model.Images));
    </script>

    @Scripts.Render("~/bundles/projectCardJs")
   
    <script>
        lightbox.option({
            'resizeDuration': 100,
            'wrapAround': true,
            'albumLabel': "Zrzut ekranu %1 z %2"
        })
    </script>
}

PortfolioMVC5v3/Views/Project/Index.cshtml
@model System.Collections.Generic.List<PortfolioMVC5v3.Models.ViewModels.ProjectViewModel>

@{
    ViewBag.Title = "Projekty";
}

@section AdditionalCss
{
    <style>
        .slide {
            background: linear-gradient(0, rgba(40, 38, 43, 0.85), rgba(40, 38, 43, 0.85)), url(/assets/backgrounds/fourth-bg.png) no-repeat center center fixed !important;
            background-size: cover;
        }
    </style>
}

<div class="slide">
    <div class="content projects-content">
        <div class="container-fluid">
            <div class="col-md-12">
                @{
                    int i = 0;
                    foreach (var project in Model)
                    {

                        var iconSrc = "/Assets/img/Icons/Placeholder.png";
                        if (project.Icon != null && project.Icon.IconId > 0)
                        {
                            iconSrc = string.Format("/Assets/Icons/{0}{1}", project.Icon.Guid, project.Icon.FileName);
                        }


                        <div>
                            <div class="row mb-5">
                                @if (i % 2 == 0)
                                {
                                    <div class="col-md-2">
                                        <div class="left-image">
                                            <img src="@iconSrc" alt="projectIcon" />
                                        </div>
                                    </div>
                                }

                                <div class="col-md-10">
                                    <div class="left-content @(i%2 == 0 ? "right-content" : "left-content")">
                                        <h2 class="mb-1">@project.Title</h2>
                                        @if (project.Technologies != null && project.Technologies.Count > 0)
                                        {
                                            <div style="color:white" class="mb-1">
                                                <b class="mr-2">Technologie:</b> <em>@string.Join(", ", project.Technologies.Take(3).Select(a => a.Name))...</em>
                                            </div>
                                        }
                                        <p>
                                            @project.ShortDescription
                                        </p>
                                        <div class="details-btn">
                                            <a href="@Url.Action("Card", "Project", new { id = project.ProjectId})">Szczegóły</a>
                                        </div>
                                    </div>
                                </div>

                                @if (i % 2 != 0)
                                {
                                    <div class="col-md-2">
                                        <div class="right-image">
                                            <img src="@iconSrc" alt="ProjectIcon" />
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>

                        i++;
                    }
                }
            </div>
        </div>
    </div>
</div>

PortfolioMVC5v3/Views/Project/ProjectManagement.cshtml
@model bool

@{
    ViewBag.Title = "Projekty";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section AdditionalCss
{
    <style>
        .k-header .k-link {
            text-align: center;
        }

        td {
            text-align: center;
        }
    </style>
}


<div class="row h-100">
    <div class="col-12">
        <div class="card" style="height: 90%">
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <h2 class="card-title">Projekty</h2>
                    </div>
                </div>

                <div class="row h-100">
                    <div class="col">
                        <div id="grid"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts
{
    <script>
        var isTempProjectPage = @Html.Raw(Json.Encode(@Model));
    </script>

    <script src="~/Scripts/admin/ProjectManagement/List.js"></script>
}